### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by pjw-cmd** [IDKiro/action-recognition-pytorch#3]
---------------------------------------------------Training---------------------------------------------------
Traceback (most recent call last):
  File "train.py", line 209, in <module>
    train(train_loader, model, criterion, optimizer, epoch)
  File "train.py", line 68, in train
    output = model(input_var)
  File "/home/pjw/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pjw/anaconda3/action-recognition-master/model.py", line 72, in forward
    fs = torch.zeros(inputs[0].size(0), length, self.rnn.input_size).cuda()
IndexError: list index out of range

**Comment by pjw-cmd** [comment]
Downloader from github, I have not modified the code. I don't know how to solve this error. For answer,thank you .

**Comment by IDKiro** [comment]
Have you downloaded the dataset and process it

**Comment by pjw-cmd** [comment]
That is the data isn't processed well, and it is ready to run now, thank you.
